version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    networks:
      - urlshortener
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  urlservice:
    build:
      context: .
      dockerfile: services/urlservice/Dockerfile
    container_name: url_shortener_urlservice
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - urlshortener
    environment:
      - REDIS_ADDR=redis:6379
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: unless-stopped

  analytics:
    build:
      context: .
      dockerfile: services/analytics/Dockerfile
    container_name: url_shortener_analytics
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - urlshortener
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: url_shortener_gateway
    depends_on:
      - urlservice
      - analytics
      - redis
    networks:
      - urlshortener
    environment:
      - REDIS_ADDR=redis:6379
      - URL_SERVICE_ADDR=urlservice:8081
      - ANALYTICS_SERVICE_ADDR=analytics:8082
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: url_shortener_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Наш конфиг (статичный, без шаблонов)
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      # Статика
      - ./web/static:/var/www/static
      # СЕРТИФИКАТЫ (Безопасное хранение вне проекта)
      - /home/deploy/certs:/etc/nginx/ssl
    depends_on:
      - gateway
    networks:
      - urlshortener
    # Команда запуска (простая, без релоадов certbot-а)
    command: nginx -g "daemon off;"
    restart: unless-stopped

networks:
  urlshortener:
    driver: bridge